[project]
name = "executorch-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nick Cao", email = "nickcao@nichi.co" }
]
requires-python = ">=3.13"
dependencies = [
    "executorch>=1.2.0.dev20260212",
]

[project.scripts]
executorch-benchmark = "executorch_benchmark:main"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/nightly"

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"
