[project]
name = "executorch-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nick Cao", email = "nickcao@nichi.co" }
]
requires-python = ">=3.13"
dependencies = [
    "executorch>=1.1.0",
    "fastapi[standard]>=0.129.0",
    "vllm>=0.15.1",
]

[project.scripts]
executorch-benchmark = "executorch_benchmark:main"

[tool.uv]
override-dependencies = [
    "torch>=2.10.0",
]

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "huggingface-hub>=0.36.2",
    "optimum>=1.27.0",
    "optimum-executorch>=0.1.0",
    "pillow>=12.1.1",
]
